[project]
name = "memx"
version = "0.1.1"
description = "Lightweight and agnostic memory layer for LLMs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "aiosqlite>=0.21.0",
    "pymongo>=4.15.3",
    "pytest>=8.4.2",
    "ruff>=0.14.2",
    "sqlalchemy>=2.0.44",
]
